services:
  app:
    build: .

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      - postgres

    volumes:
      - .:/app
      - /app/node_modules

    command: npm run dev

  postgres:
    image: postgres:16

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: audit_log_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: